#!/bin/sh

# PARAMS
ALL_HOSTS="/var/www"
DIR_SITES_ENABLED="/etc/apache2/sites-enabled"
DIR_SITES_AVAILABLE="/etc/apache2/sites-available"
FILE_HOSTS="/etc/hosts"

if [ $# -eq 0 ] || [ "$1" = "--help" ] || [ "$1" = "-h" ] ; then
	echo "HELP
usage: addserv [--del [--live-core-dir]] HOST_NAME [--no-index-create] [ DOCUMENT_ROOT ]

	DOCUMENT_ROOT 		working directory, by default $ALL_HOSTS/[HOST_NAME]/
	can be $ALL_HOSTS/[HOST_NAME]/[DOCUMENT_ROOT]
=============================================================================
	--no-index-create, -i		no index create
	--del, -d		remove Virtual host
	--live-core-dir, -l		Leave core dir
"
	exit 0
fi


init()
{	
	echo "init vars"
	HOST_NAME="example-`date +%s`"
	if [ $# -gt 0 ]; then
		HOST_NAME=$1
		shift 1
	fi
	
	echo "set HOST_NAME: $HOST_NAME"
	
	CORE_DIR="$ALL_HOSTS/$HOST_NAME"
	
	echo "set CORE_DIR: $CORE_DIR"
	CREATE_INDEX_FILE=1
	
	if [ $# -gt 0 ]; then
		if [ "$1" = "--no-index-create" ] || [ "$1" = "-i" ]  ; then
			CREATE_INDEX_FILE=0
			shift 1
		fi
	fi
	
	if [ $# -gt 0 ]; then
		DOCUMENT_ROOT="$CORE_DIR/$1"
		shift 1
	else
		DOCUMENT_ROOT="$CORE_DIR"
	fi
	
	echo "set DOCUMENT_ROOT: $DOCUMENT_ROOT"
	
	if [ $# -gt 0 ]; then
		PORT="$1"
		shift 1
	else
		PORT=80
	fi
	
	echo "set PORT: $PORT"
} 


addHost()
{

	mkdir -p $CORE_DIR
	echo "---"
	echo "Create CORE_DIR"

	
	mkdir -p $DOCUMENT_ROOT

	echo "---"
	echo "Create DOCUMENT_ROOT if not same whith CORE_DIR"
	
	if [ $CREATE_INDEX_FILE -eq 1 ] ; then
		generateExampleIndex
	fi 

	generateVirtualHostConfig

	addNewHostNameToHosts


	echo "---"
	echo "add and restart server"

	a2ensite "$HOST_NAME.conf"

	service apache2 restart
	service apache2 reload

}





generateExampleIndex()
{
	echo "<html>
	  <head>
		<title>Welcome to Example.com!</title>
	  </head>
	  <body>
		<h1>Success!  The $HOST_NAME virtual host is working!</h1>
	  </body>
	</html>" > "$DOCUMENT_ROOT/index.php"
	
		
	echo "---"
	echo "Create index.php in $DOCUMENT_ROOT"
	
}
generateVirtualHostConfig()
{

	VIRTHOST_DATA="
	<VirtualHost *:$PORT>
		ServerAdmin admin@$HOST_NAME
		ServerName $HOST_NAME
		ServerAlias www.$HOST_NAME
		DocumentRoot $DOCUMENT_ROOT
		<Directory $DOCUMENT_ROOT>
			Options Indexes FollowSymLinks MultiViews
			AllowOverride All
			Order allow,deny
			allow from all
		</Directory>

		ErrorLog \${APACHE_LOG_DIR}/error.log
		CustomLog \${APACHE_LOG_DIR}/access.log combined
	</VirtualHost>
	# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
	"

	echo "$VIRTHOST_DATA" > "$DIR_SITES_AVAILABLE/$HOST_NAME.conf"
	
	echo "---"
	echo "Create configuration file"
}

readLine()
{	
	if [ "$2" != "$HOST_NAME" ] && [ "$1$2$3" != "" ]; then

HOSTS_DATA="$HOSTS_DATA 
$1 $2 $3";


	fi
}

addNewHostNameToHosts()
{
	HOSTS_DATA=`cat $FILE_HOSTS`
	echo "$HOSTS_DATA
	127.0.0.1 $HOST_NAME" > "$FILE_HOSTS"
		
	echo "---"
	echo "$HOST_NAME to hosts"
}

# start

if [ $(id -u) -ne 0 ] ; then
	echo "Please run as root" ; exit 1 ; 
fi


if [ $# -ge 2 ] ; then	
	if [ "$1" = "-d" ] || [ "$1" = "--del" ]  ; then	
		echo "$1"	
		shift 1;
		REMOVE_CORE_DIR=1

		if [ "$1" = "--live-core-dir" ] || [ "$1" = "-l" ]  ; then	
			REMOVE_CORE_DIR=0
		fi
		
		echo "remove '$1'"

		init $@		

		HOSTS_DATA=""

		while read LINE;
			do readLine $LINE;

		done < /etc/hosts

		echo "$HOSTS_DATA" > "$FILE_HOSTS"
		if [ -f "$DIR_SITES_ENABLED/$HOST_NAME.conf" ] ; then
			rm "$DIR_SITES_ENABLED/$HOST_NAME.conf"
		fi

		if [ -f "$DIR_SITES_AVAILABLE/$HOST_NAME.conf" ] ; then
			rm "$DIR_SITES_AVAILABLE/$HOST_NAME.conf"
		fi

		if [ $REMOVE_CORE_DIR -eq 1 ] && [ -d "$CORE_DIR" ] ; then
			rm -rf "$CORE_DIR"
		fi

		service apache2 restart
		service apache2 reload

		exit 0 ; 
	fi
fi

echo "start"
init $@
addHost $@




